"""is-active-field-league

Revision ID: 0e90cf0d5b3d
Revises: a2fdff55ec71
Create Date: 2025-04-04 22:13:48.441852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e90cf0d5b3d'
down_revision: Union[str, None] = 'a2fdff55ec71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'is_active')
    # ### end Alembic commands ###
