"""forgot-lock-date

Revision ID: a2fdff55ec71
Revises: 582a93a2087b
Create Date: 2025-04-04 21:11:49.527589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2fdff55ec71'
down_revision: Union[str, None] = '582a93a2087b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('lock_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'lock_date')
    # ### end Alembic commands ###
